### ISSUE TITLE
cgiNodeInfo is not defined

### ISSUE THREAD

**Issue by odan** [UeiRicho/cgi-node#1]
Hello

The docs on http://www.cgi-node.org/ says: 

"Like phpInfo(), cgiNodeInfo() will display all the server variables, request headers, query sting, POST forms and POST files."

<? cgiNodeInfo() ?>

EXCEPTION: cgiNodeInfo is not defined
ReferenceError: cgiNodeInfo is not defined

But this will work:

<? CgiNodeInfo() ?>

**Comment by deda-ca** [comment]
Thanks odan for finding the issue and thank you, joridos for the fix. It has been merged into the code.

**Comment by zimorodokan** [comment]
<? cgiNodeInfo() ?> not works
<? CgiNodeInfo() ?> works
Please, update docs on http://www.cgi-node.org/home

**Comment by 2pay** [comment]
not works.

Error: 

`EXCEPTION: cgiNodeInfo is not defined
ReferenceError: cgiNodeInfo is not defined
    at /home/xxx/public_html/cgiNodeInfo.jss:1:2
    at ContextifyScript.Script.runInContext (vm.js:37:29)
    at Object.exports.runInContext (vm.js:69:17)
    at CgiHttpContext.include (/home/xxx/public_html/cgi-bin/cgi-node.js:5:125)
    at onReady (/home/xxx/public_html/cgi-bin/cgi-node.js:19:446)
    at Object. (/home/xxx/public_html/cgi-bin/cgi-node.js:20:75)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)`

**Comment by YuriGor** [comment]
**C**giNodeInfo actually starts with capital 'C'
