### ISSUE TITLE
GoDaddy cgiNodeInfo.jscript not working correctly

### ISSUE THREAD

**Issue by richm617** [UeiRicho/cgi-node#20]
I right click on cgiNodeInfo.jscript from my CPanel and click View and all I see is the following:
Could you help?
![1](https://cloud.githubusercontent.com/assets/14356529/9976517/6a0276b4-5eb4-11e5-9785-e811336479fb.JPG)
![2](https://cloud.githubusercontent.com/assets/14356529/9976518/6a080598-5eb4-11e5-9ebe-2905fe605a6a.JPG)
![3](https://cloud.githubusercontent.com/assets/14356529/9976522/6a09d27e-5eb4-11e5-86ae-1393c91f2bf9.JPG)
![4](https://cloud.githubusercontent.com/assets/14356529/9976521/6a09a678-5eb4-11e5-9725-6fb48e8524e3.JPG)
![5](https://cloud.githubusercontent.com/assets/14356529/9976519/6a08ab4c-5eb4-11e5-9c70-cb5912c1ef52.JPG)
![6](https://cloud.githubusercontent.com/assets/14356529/9976520/6a0910f0-5eb4-11e5-95a8-3db7e575b9ef.JPG)

**Comment by lanled** [comment]
I have the same problem

Lan

**Comment by lanled** [comment]
I think that the problem is i the file cgi-node.js 

Lan

**Comment by lanled** [comment]
BTW I use bluehost

**Comment by jaszhix** [comment]
If you are using the version from the website, it is not as up to date as the one from this repo. cgiNodeInfo() works on the repo version, where as CgiNodeInfo() works on the version on the website. I suggest cloning this repo instead.

**Comment by richm617** [comment]
Thanks but can you help me a little more? I've found cgiNodeInfo()  in this repo but all it says is 
 1 lines (1 sloc) 20 Bytes
<? CgiNodeInfo(); ?>

What do I do with that?  It's from oct 15 2014

**Comment by jaszhix** [comment]
It looks like node is not being executed and your files are being loaded as plain text. I took another look at the screenshots you posted. You need to point your cgi-node.js file directly to node. So it should look like:

```
#!/home/wmoralespr/bin/node
```

I'm assuming all of the libs node needs is in wmoralespr. Make sure your files are chmod 755. If you use the version from this repo in cgi-bin/, rename your extension JSS on files and in .htaccess, or change JSS to jscript in cgi-node.js.

**Comment by richm617** [comment]
I changed the cgi-node.js to point to node.  It still just showed as before
 I'm not sure how to change it stop loading from plain text?   I've not changed to your repo yet.

Attached is what libs I have.
![capture](https://cloud.githubusercontent.com/assets/14356529/10036326/0061edc6-6174-11e5-8bf0-11298bf30431.JPG)

**Comment by jaszhix** [comment]
This is not my repo. :) I would be pointing your browser to the public address of the jscript file on port 80. It likely will not do anything from cpanel.

**Comment by richm617** [comment]
Could I give you remote access?

**Comment by richm617** [comment]
SessionPath:"/home/wmoralespr/bin/" I assume should also be /home/wmoralespr/bin/node

**Comment by jaszhix** [comment]
SessionPath needs its own directory, create a dir like /home/wmoralespr/sessions, then point SessionPath to that. I am just helping because I like this project, and don't like seeing people get stuck, but I can't play a tech support role.

**Comment by richm617** [comment]
I hear you.  I've changed the session path. 
I am not sure how to do the clone of cgi-info though. 
![capture](https://cloud.githubusercontent.com/assets/14356529/10036456/18d7016e-6176-11e5-85ff-2c67d3489e6e.JPG)
![capture1](https://cloud.githubusercontent.com/assets/14356529/10036455/18d300dc-6176-11e5-8e07-0c0a4d40cd09.JPG)

**Comment by jaszhix** [comment]
Paste your cgi-node.js file here: http://0bin.net/ and give me the long URL in the address bar. Did you try going to your site's public address? .htaccess only works there.

**Comment by richm617** [comment]
https://p3plcpnl0462.prod.phx3.secureserver.net:2083/cpsess8901585666/frontend/gl_paper_lantern/filemanager/showfile.html?file=cgi-node.js&fileop=&dir=%2Fhome%2Fwmoralespr%2Fpublic_html%2Fcgi-bin&dirop=&charset=&file_charset=&baseurl=&basedir=

**Comment by richm617** [comment]
23.229.176.101 my public address

**Comment by jaszhix** [comment]
You gave me the link to your godaddy account. Paste/upload your cgi-node.js file to 0bin?

What are you trying to use cgi-node for? I wouldn't use cgi-node unless you absolutely have to. Its really just a jerry rigged version of node for CGI - not maintained, and probably not something to run in production if you're not familiar with linux.

**Comment by richm617** [comment]
I posted to the 0bin

**Comment by richm617** [comment]
I'm going to send data to the site and have it display live results for races.  i used it locally on my machine and it worked well for what I want, I'm trying to get the WAN to work now.

**Comment by jaszhix** [comment]
http://23.229.176.101/cgiNodeInfo.jscript gives a 404. You didn't give me a 0bin link, so I can't look at what you pasted or uploaded.

**Comment by richm617** [comment]
I uploaded to the 0bin link you had me click on

**Comment by jaszhix** [comment]
Now paste the long link here it redirects to.

**Comment by richm617** [comment]
![capture](https://cloud.githubusercontent.com/assets/14356529/10036736/8ffd8576-6179-11e5-84fa-5104325bcc6f.JPG)

**Comment by richm617** [comment]
http://0bin.net/paste/mUsH5mrLDDRv6lEi#nm-qlbju44ufYmPkHSa8NiOVUwYAwp0HR74IaiiJWyX

**Comment by jaszhix** [comment]
I formatted it and changed line 8. It was using JSS. Not really your fault, the documentation is completely wrong.

http://0bin.net/paste/NoKzctPiDhA0vEG6#vOPssEHewHnoG6SbZOeRRY0+zcAX+ao4LsORu7ZMu3N

**Comment by richm617** [comment]
i'm getting the same as before is that right?  I click view and get the following?
![capture](https://cloud.githubusercontent.com/assets/14356529/10036813/da0f4d24-617a-11e5-86b6-8e4df106d213.JPG)
![capture1](https://cloud.githubusercontent.com/assets/14356529/10036814/da15418e-617a-11e5-8e21-bdc1d5677626.JPG)

**Comment by jaszhix** [comment]
I would really suggest not using screenshots. You should try to use FTP or SSH. Nothing you view in cpanel will work with node - cgi-node only works on port 80, because that's what htaccess is configuring.

**Comment by richm617** [comment]
I thought it would open up in a browser the contents of the server it's running on.

**Comment by jaszhix** [comment]
> https://p3plcpnl0462.prod.phx3.secureserver.net:2083/cpsess8901585666/frontend/gl_paper_lantern/filemanager/showfile.html?file=cgi-node.js&fileop=&dir=%2Fhome%2Fwmoralespr%2Fpublic_html%2Fcgi-bin&dirop=&charset=&file_charset=&baseurl=&basedir=

the :2083 at the end of the hostname (p3plcpnl0462.prod.phx3.secureserver.net) is the port. You gave me the server's IP, so anything in /home/wmoralespr should be available at http://23.229.176.101/ (port 80)

**Comment by richm617** [comment]
correct. I thought going http://23.229.176.101/cgiNodeInfo.jscript would at least try to call up the script and make it run

**Comment by jaszhix** [comment]
```
<? CgiNodeInfo() ?>
```

**Comment by richm617** [comment]
yes i thought it would run that and then display the contents of the machine.  I tried to even put the /public_html/cginodeinfo.jscript

**Comment by jaszhix** [comment]
I'm sorry?

**Comment by richm617** [comment]
lol Ya, I'm sorry to
![capture](https://cloud.githubusercontent.com/assets/14356529/10036977/39f74d84-617d-11e5-980f-dfe120c54bbf.JPG)
o this thing doesn't work as it should.  It's supposed to show

**Comment by jaszhix** [comment]
That's on godaddy? That means its working.

**Comment by richm617** [comment]
haha. not that's the tutorial on how to do this but it doesn't work. http://www.cgi-node.org/docs/cgi-node-on-godaddy-tutorial

**Comment by jaszhix** [comment]
I think it was disingenuous for the author to suggest cgi-node should be installed by anyone -- and configured over web admin. Node is linux software, and you need a terminal for this stuff.

**Comment by richm617** [comment]
Ya, it seems like i wasted a lot of time on it.  They make it look so easy.  I mean I am entering the correct navigation link right? http://23.229.176.101/cginodeinfo.jscript

**Comment by jaszhix** [comment]
Yeah, except for the case sensitivity, cgiNodeInfo.jscript would make a difference in a nix environment.

**Comment by richm617** [comment]
when I use the domainname/cgiNodeInfo.jscript
I get:
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@XXXXXX.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by jaszhix** [comment]
Did you install node? This is probably your only option on godaddy - https://github.com/niutech/node.php if you don't want to use SSH.

**Comment by richm617** [comment]
this never ends!  When I try to install it I get:
Node.php

Node.js is not yet installed. Switch to Admin Mode and Install it.

Powered by node.php

**Comment by jaszhix** [comment]
Edit node.php https://github.com/niutech/node.php/blob/master/node.php#L13 - change it to true, then back to false after you install node.

**Comment by richm617** [comment]
Thanks. Got it installed but for line two: When succeeded, install your node.js app by uploading its folder or using npm: http://example.org/node.php?npm=install jt-js-sample

I get

Node.php

Running: npm node/bin/npm install jt-js-sample
Failed. Error: 127

**Comment by jaszhix** [comment]
https://github.com/niutech/node.php/issues/4

**Comment by richm617** [comment]
I don't have the SSL credentials. i'll need to call GoDaddy and do it tomorrow. Thank you for your help!

**Comment by jaszhix** [comment]
Np, good luck!

**Comment by richm617** [comment]
Can I used FTP for line 2? GoDaddy is telling me I don't have SSL

When succeeded, install your node.js app by uploading its folder or using npm: http://example.org/node.php?npm=install jt-js-sample.

**Comment by jaszhix** [comment]
SSH.

**Comment by rokeegithub** [comment]
i am having 404 error while following all the instruction given here if you want i can post cgi-node.js file to bin can you please help me

**Comment by webtech0101** [comment]
After follow http://www.cgi-node.org/docs/cgi-node-on-godaddy-tutorial showing error 

HOW CAN I SOLVE THAT 

EXCEPTION: ENOENT: no such file or directory, open <br>'/home/<path>/bin/sessions/c3b705ce7c3920962bcec27021d8d3fb'
Error: ENOENT: no such file or directory, open '/home/<path>/bin/sessions/c3b705ce7c3920962bcec27021d8d3fb'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at CgiHttpSession.create (/home/<path>/public_html/cgi-bin/cgi-node.js:343:6)
    at CgiHttpSession.init (/home/<path>/public_html/cgi-bin/cgi-node.js:294:44)
    at new CgiHttpSession (/home/<path>/public_html/cgi-bin/cgi-node.js:378:7)
    at new CgiHttpContext (/home/<path>/public_html/cgi-bin/cgi-node.js:118:17)
    at Object. (/home/<path>/public_html/cgi-bin/cgi-node.js:948:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

Content-type: text/html; charset=iso-8859-1 
EXCEPTION: Cannot read property 'session' of null
TypeError: Cannot read property 'session' of null
    at process. (/home/<path>/public_html/cgi-bin/cgi-node.js:941:16)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)

**Comment by dotme** [comment]
@webtech0101 I am not a great specialist but I want to give you a little help with your problem. It all looks like you should edit the cgi-node.js file to have the working server. Check path to sessions and replace it with yours. Look [here](http://forum.centos-webpanel.com/addons/installation-node-js-and-integration/msg8553/#msg8553) it is short instructions to solve your problem. Sessions folder must be separated from other folders and needs to 755 permissions.
Have a nice day.
