### ISSUE TITLE
cannot use modules in CGI-Node

### ISSUE THREAD

**Issue by nijo** [UeiRicho/cgi-node#43]
I am getting an error while using CGI-Node to work with MongoDB.

EXCEPTION: Cannot find module 'mongodb'
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'mongodb'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at C:\wamp64\www\Learning_Document5\server.js:1:19
    at Script.runInContext (vm.js:102:20)
    at Object.runInContext (vm.js:280:6)
    at CgiHttpContext.include (C:\wamp64\cgi-bin\cgi-node.js:170:6)
    at onReady (C:\wamp64\cgi-bin\cgi-node.js:951:43)
    at Object. (C:\wamp64\cgi-bin\cgi-node.js:957:46)
I check same by using node cmd and it worked

**Comment by nijo** [comment]
Had to specify absolute path to all modules to make it work.

**Comment by PogromistDev** [comment]
It's like cgi-node.js executes .jss files but doesn't change his working directory. It reads from /cgi-bin/
